### PR TITLE
Convert to npm module

### PR DESCRIPTION
**Pull request by taksuparth**
Convert to npm module:  (#21)

Changes done: 

1. Moved code to `packages/Linkees` which will act as a module
2. Added webpack build, tsConfig and added entry point of a module
3. Added prettier pre-commit hook
4. Defined and exposed `CHANNEL_TYPES` to save redundant work.
5. Used published package in current website

### CODE REVIEW

**Comment by heysagnik** [comment]
Why the deployment is failing?
> [13:46:57] Cloning github.com/heysagnik/Linkees (Branch: convert-to-modules, Commit: a4564a9)
[13:46:57] Cloning completed: 511.136ms
[13:46:58] Looking up build cache...
[13:47:01] Build cache downloaded [61.20 MB]: 3345ms
[13:47:01] Running "vercel build"
[13:47:02] Vercel CLI 28.4.12-cc30642
[13:47:02] Installing dependencies...
[13:47:03] yarn install v1.22.17
[13:47:03] info No lockfile found.
[13:47:03] [1/4] Resolving packages...
[13:47:07] warning react-scripts > @svgr/webpack > @svgr/plugin-svgo > svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
[13:47:08] warning react-scripts > @svgr/webpack > @svgr/plugin-svgo > svgo > stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
[13:47:09] warning react-scripts > css-minimizer-webpack-plugin > cssnano > cssnano-preset-default > postcss-svgo > svgo > stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
[13:47:09] warning react-scripts > jest > @jest/core > jest-config > jest-environment-jsdom > jsdom > w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
[13:47:10] [2/4] Fetching packages...
[13:47:22] [3/4] Linking dependencies...
[13:47:22] warning " > @testing-library/user-event@13.5.0" has unmet peer dependency "@testing-library/dom@>=7.21.4".
[13:47:22] warning " > react-dom@16.14.0" has incorrect peer dependency "react@^16.14.0".
[13:47:22] warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-syntax-flow@^7.14.5".
[13:47:22] warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-transform-react-jsx@^7.14.9".
[13:47:37] [4/4] Building fresh packages...
[13:47:40] success Saved lockfile.
[13:47:40] Done in 37.38s.
[13:47:40] Running "yarn run build"
[13:47:40] yarn run v1.22.17
[13:47:40] $ react-scripts build
[13:47:42] Creating an optimized production build...
[13:47:45] Failed to compile.
[13:47:45] 
[13:47:45] Module not found: Error: Can't resolve 'linktree-test' in '/vercel/path0/src'
[13:47:45] 
[13:47:45] 
[13:47:45] error Command failed with exit code 1.
[13:47:45] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[13:47:45] Error: Command "yarn run build" exited with 1

**Comment by taksuparth** [comment]
@heysagnik checking deployment failures

**Comment by taksuparth** [comment]
@sametcodes this can be checked now! Package is published https://www.npmjs.com/package/linkees

**Comment by heysagnik** [comment]
here is my email `sahoosagnik1@gmail.com`
Thanks a lot converting this into a npm module. I had no idea regarding module making , but most of the users requested it .
Thanks a lot, this means a lot to me

**Comment by taksuparth** [comment]
@heysagnik can you please signup on https://www.npmjs.com ? Not able to find your user on npm

**Comment by heysagnik** [comment]
> @heysagnik can you please signup on https://www.npmjs.com ? Not able to find your user on npm

Check once again See https://www.npmjs.com/~heysagnik

**Comment by sametcodes** [comment]
> @sametcodes this can be checked now! Package is published https://www.npmjs.com/package/linkees. Please singup on npm and provide me your email address, so that I can add you as maintainer

Hey, it's hey@samet.codes, thank you!

**Comment by taksuparth** [comment]
@heysagnik I've added you as a maintainer. @sametcodes npm is not able to search users from email address. Can you please share your username? Like https://www.npmjs.com/~heysagnik

**Comment by sametcodes** [comment]
> @heysagnik this can be checked now! Package is published https://www.npmjs.com/package/linkees. Please singup on npm and provide me your email address, so that I can add you as maintainer

I really wonder what's the purpose of publishing the repository as an npm module. Could you elaborate, please?

**Comment by heysagnik** [comment]
> > @heysagnik this can be checked now! Package is published https://www.npmjs.com/package/linkees. Please singup on npm and provide me your email address, so that I can add you as maintainer
> 
> I really wonder what's the purpose of publishing the repository as an npm module. Could you elaborate, please?

Many of the user asked for a npm module, So @taksuparth converted it into the module

**Pull request merged**
